### ISSUE TITLE
Extend exterminator script to accept gh repo as input

### ISSUE THREAD

**Issue by lianmakesthings** [tilt-dev/exterminator#11]
We want to be able to import github issues for other repos (such as tilt-extensions) into shortcut as well

**Comment by nicks** [comment]
TBH, I think it's reasonable to add this. you could either add the repo as a flag, or change the API so that you need to pass a full issue URL instead of an issue number

But I've also wondered if we should have some sort of webservice that does the syncing automatically, rather than continuing to invest in a manual CLI

**Comment by nicksieger** [comment]
Manual still feels appropriate. Only the issues that we're working on or that might require further prioritization as part of a larger epic need to be synchronized.

**Comment by lianmakesthings** [comment]
Agree with @nicksieger. We want to make sure we have all the information (and edit the description if necessary) before we create a story in shortcut, imho.
